{{- if .Values.pipeline.enabled }}
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: Upload a Pipeline to a KFP cluster
    tekton.dev/pipelines.minVersion: '0.19'
    tekton.dev/tags: 'kfp'
  name: kfp-upload
  namespace: {{ $.Values.project.name }}
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: redhat
spec:
  description: >-
    These Task will compile and upload a Pipeline to a KFP cluster
  params:
    - description: The image used where python is installed
      name: TASK_IMAGE
      type: string
      default: tensorflow/tensorflow
    - description: The pipeline python script to compile
      name: PIPELINE_NAME
      type: string
      default: get_data_train_upload
    - description: The requiretments file to install
      name: REQUIREMENTS_FILE
      type: string
      default: requirements.txt
    - description: The path to the pipeline python script
      name: PIPELINES_PATH
      type: string
      default: pipeline
  results:
    - description: The Pipeline Id of the kfp pipeline uploaded
      name: PIPELINE_ID
  steps:
    - image: $(params.TASK_IMAGE)
      timeout: 10m0s
      name: compile
      workingDir: $(workspaces.source.path)
      computeResources: {}
      env:
        - name: PIPELINE_NAME
          value: $(params.PIPELINE_NAME)
        - name: PIPELINES_PATH
          value: $(params.PIPELINES_PATH)
      script: |
        #!/bin/sh

        echo "Compiling pipeline $(params.PIPELINE_NAME).yaml"

        echo "Current directory"
        pwd

        echo "List files"
        ls -lstrh

        cd $(params.PIPELINES_PATH)

        pip install -r $(params.REQUIREMENTS_FILE)

        # Upload the pipeline
        export NAMESPACE_NAME="$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)"
        export TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
        export PIPELINE_NAME="$(params.PIPELINE_NAME)"

        echo "NAMESPACE_NAME: $NAMESPACE_NAME PIPELINE_NAME: $PIPELINE_NAME TOKEN: $TOKEN"

        python $(params.PIPELINE_NAME).py $TOKEN
  workspaces:
    - mountPath: /workspace/source
      name: source
{{- end }}
