apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-run-{{ .Values.pipeline.name }}
  namespace: {{ $.Values.project.name }}
spec:
  params:
    - description: Model version
      name: MODEL_VERSION
      type: string
      default: '1' 
    - description: Card transaction data
      name: CARDTRANSDATA
      type: string
  tasks:
    - name: kfp-run-pipelines
      taskRef:
        kind: Task
        name: kfp-run-pipelines
      params:
        - name: CARDTRANSDATA
          value: $(params.CARDTRANSDATA)
        - name: MODEL_VERSION
          value: $(params.MODEL_VERSION)          


