#!/bin/bash
echo 1


# Define the namespace and label
NAMESPACE="fraud"
LABEL="initial=true"
kubectl get pods -n "$NAMESPACE" -l "$LABEL" --no-headers

# Check if there is a pod with the specified label in the specified namespace
if ! kubectl get pods -n "$NAMESPACE" -l "$LABEL" --no-headers | grep -q '^'; then
    echo "ok"
fi

