apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-fraud-example
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source: 
    path: ai-examples/charts/onboard-datascience
    repoURL: 'https://github.com/davidseve/mlops.git'
    targetRevision: pipeline #TOODO change to main
    helm:
      valueFiles:
      - ../../fraud-detection/gitops/values-fraud.yaml  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true