# openshift user using the project - to add the right user in the UI
user: kubeadmin
clusterURL: https://rhods-dashboard-redhat-ods-applications.apps.cluster-87xpx.87xpx.sandbox1137.opentlc.com
project:
  # name of the data scienece project
  name: fraud-mult
  # true if project doesn't exist now
  autocreate: true
inference:
  dataconnections: dataconnection-one
  version: 1
multimodel: true
notebooks:
  - notebook-one:
    enabled: true
      # name of the workbench
    name: workbench-one
      # image used by the workbench
    image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/tensorflow:2024.1
    size: Small
      # resorces added to the notebook pod
    resources:
      limits:
        gpu: 0 # set to 0 to disable gpu
        cpu: '2'
        memory: 8Gi
      requests:
        cpu: '1'
        memory: 8Gi
    storage:
      # storage name if storage is enabled
      name: storage-workbench-one
      # storage size if storage is enabled
      size: 20Gi
    dataconnections:
      - dataconnection-one
dataconnections:
  - dataconnection-one:
    # name of the data connection
    name: dataconnection-one
    data:
      AWS_ACCESS_KEY_ID: minio #from create-root-user-job.yaml MINIO_ROOT_USER
      AWS_DEFAULT_REGION: eu-south-2
      AWS_S3_BUCKET: dataconnection-one
      AWS_S3_ENDPOINT: minio.minio.svc.cluster.local:9000
      AWS_SECRET_ACCESS_KEY: minio123 #from create-root-user-job.yaml MINIO_ROOT_PASSWORD    
      scheme: http
pipeline:
  # enable / diable pipeline
  enabled: true
  #dspa
  name: pipeline-one  
  dataconnection:
    data:
      AWS_ACCESS_KEY_ID: minio #from create-root-user-job.yaml MINIO_ROOT_USER
      AWS_DEFAULT_REGION: eu-south-2
      AWS_S3_BUCKET: pipeline-one
      AWS_S3_ENDPOINT: minio.minio.svc.cluster.local:9000
      AWS_SECRET_ACCESS_KEY: minio123 #from create-root-user-job.yaml MINIO_ROOT_PASSWORD   
      scheme: http
  #Tekton pipeline
  repo: https://github.com/davidseve/mlops.git
  revision: main
  gitSslVerify: true
  pipelinePath: ai-examples/fraud-detection/pipeline
  pythonPipelineName: get_data_train_upload.py
  sourceWorkspaceSize: 2Gi